################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 5 - Production/Stable",
		"License :: OSI Approved :: Apache Software License",
	],
	description = "Python module to run command line programs in a very convenient way.",
	download_url = "https://github.com/jkpubsrc/python-module-jk-simpleexec/tarball/0.2019.9.12",
	include_package_data = False,
	install_requires = [
		"lxml",
	],
	keywords = [
		"exec",
		"shell",
		"execute",
		"Popen",
	],
	license = "Apache 2.0",
	name = "jk_simpleexec",
	packages = [
		"jk_simpleexec",
	],
	url = "https://github.com/jkpubsrc/python-module-jk-simpleexec",
	version = "0.2019.9.12",
	zip_safe = False,
	long_description = readme(),
	long_description_content_type="text/markdown",
)
