################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 5 - Production/Stable",
		"License :: OSI Approved :: Apache Software License",
		"Programming Language :: Python :: 3",
	],
	description = "Python module to run command line programs in a convenient way and retrieve their output after they terminated.",
	include_package_data = True,
	install_requires = [
		"invoke",
		"jk_prettyprintobj",
		"jk_cmdoutputparsinghelper",
	],
	keywords = [
		"exec",
		"shell",
		"execute",
		"Popen",
		"kill",
		"spawn",
	],
	license = "Apache2",
	name = "jk_simpleexec",
	package_data = {
		"": [
		],
	},
	packages = [
		"jk_simpleexec",
	],
	scripts = [
	],
	version = '0.2022.8.7',
	zip_safe = False,
	long_description = readme(),
	long_description_content_type = "text/markdown",
)
